farming_settings:
  active: 1
  crown_goal: 30
  last_run: 0
  playlist_length: 500
  starting_page: 1
general_settings:
  verbose: 1
stealing_settings:
  active: 1
  crown_goal: 30
  last_opponent_save: 0
  last_run: 0
  playlist_length: 500
  reuse: 7
  saved_opponent_goal: 30
